# -*- coding: utf-8 -*-
"""baseline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2Fv0xcCwcgmpV1uKIr-QaLclyOTvX2v
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile harm.py
# import json
# import re
# import time
# from typing import List, Tuple, Optional, Dict, Any
# from pydantic import BaseModel, Field, ValidationError
# 
# # ==========================================
# # STAGE 1: EXTENDED STATE BRIDGE WITH TELEMETRY
# # ==========================================
# 
# class RobotState(BaseModel):
#     """Robot telemetry state structure for safety evaluation."""
#     positions: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
#     velocity: List[float] = Field(default_factory=lambda: [0.0, 0.0, 0.0])
#     timestamp: float = Field(default_factory=time.time)
# 
# class VLMCommand(BaseModel):
#     """Standardized command object for pipeline loops."""
#     action: str = "MOVE"
#     target_object: str = "NONE"
#     waypoints: List[List[float]]
#     confidence: float = Field(default=1.0, ge=0.0, le=1.0)
#     obstacles: List[str] = Field(default_factory=list)
#     raw_response: str = ""
# 
# class HARMReceipt(BaseModel):
#     """Validation receipt generated by the HARM safety engine."""
#     status: str  # 'PASSED', 'RECOVERED', 'FALLBACK'
#     is_safe: bool = True
#     catch_type: Optional[str] = None
#     stage_failed: Optional[int] = None
#     error_type: Optional[str] = None
#     latency_ms: float = 0.0
#     command: Optional[VLMCommand] = None
#     validation_notes: List[str] = Field(default_factory=list)
# 
# 
# # ==========================================
# # STAGE 2: LATENCY & DIAGNOSTIC PROFILER
# # ==========================================
# 
# class LatencyProfiler:
#     """Telemetry logger tracking HARM validation speeds and catch statistics."""
#     def __init__(self):
#         self.latencies: List[float] = []
#         self.status_counts: Dict[str, int] = {"PASSED": 0, "RECOVERED": 0, "FALLBACK": 0}
# 
#     def record_validation(self, status: str, latency_ms: float):
#         self.latencies.append(latency_ms)
#         self.status_counts[status] = self.status_counts.get(status, 0) + 1
# 
#     def get_summary(self) -> Dict[str, Any]:
#         avg_latency = sum(self.latencies) / len(self.latencies) if self.latencies else 0.0
#         return {
#             "total_evaluations": len(self.latencies),
#             "average_latency_ms": round(avg_latency, 3),
#             "status_breakdown": self.status_counts
#         }
# 
# 
# # ==========================================
# # STAGE 3: MONITORED VLM CONTROL LOOP
# # ==========================================
# 
# class HARM:
#     """3-Stage Validation Safety Filter for VLM payloads."""
#     def __init__(self, workspace_limits: Optional[List[Tuple[float, float]]] = None):
#         # Default 3D Cartesian workspace limits in meters [X, Y, Z]
#         self.workspace_limits = workspace_limits or [(-1.0, 1.0), (-1.0, 1.0), (0.0, 1.5)]
# 
#     def _clean_raw_text(self, text: str) -> str:
#         """Extracts JSON payload from markdown or raw string formatting."""
#         text = re.sub(r'```json\s*', '', text)
#         text = re.sub(r'```\s*', '', text)
#         match = re.search(r'\{.*\}', text, re.DOTALL)
#         return match.group(0) if match else text.strip()
# 
#     def validate(self, raw_response: str, current_state: Any) -> Tuple[VLMCommand, HARMReceipt]:
#         """
#         Executes validation:
#         1. Schema parsing
#         2. Workspace boundary validation & clipping
#         3. Kinematic continuity check
#         """
#         notes = []
#         status = "PASSED"
#         t0 = time.perf_counter()
# 
#         # Handle dict or RobotState objects seamlessly
#         if isinstance(current_state, dict):
#             state_obj = RobotState(
#                 positions=current_state.get("positions", [0.0, 0.0, 0.0]),
#                 timestamp=current_state.get("timestamp", time.time())
#             )
#         elif isinstance(current_state, RobotState):
#             state_obj = current_state
#         else:
#             state_obj = RobotState(positions=[0.0, 0.0, 0.0], timestamp=time.time())
# 
#         # --- Stage 1: Schema Parsing ---
#         cleaned_text = self._clean_raw_text(raw_response)
#         try:
#             parsed_json = json.loads(cleaned_text)
#             command = VLMCommand(**parsed_json)
#         except Exception as e:
#             notes.append(f"Stage 1 Failed (JSON/Schema error: {e}). Triggering Safety Fallback.")
#             fallback_cmd = VLMCommand(
#                 action="STOP",
#                 target_object="NONE",
#                 waypoints=[state_obj.positions],
#                 confidence=0.0,
#                 raw_response=raw_response
#             )
#             elapsed_ms = (time.perf_counter() - t0) * 1000.0
#             receipt = HARMReceipt(
#                 status="FALLBACK",
#                 is_safe=False,
#                 catch_type="SCHEMA_PARSE_ERROR",
#                 stage_failed=1,
#                 error_type=type(e).__name__,
#                 latency_ms=elapsed_ms,
#                 command=fallback_cmd,
#                 validation_notes=notes
#             )
#             return fallback_cmd, receipt
# 
#         # --- Stage 2: Workspace Boundary Validation & Clipping ---
#         safe_waypoints = []
#         clipped_occurred = False
#         for wp in command.waypoints:
#             clipped_wp = []
#             for i, val in enumerate(wp):
#                 if i < len(self.workspace_limits):
#                     low, high = self.workspace_limits[i]
#                     if val < low or val > high:
#                         clipped_occurred = True
#                         val = max(low, min(val, high))
#                 clipped_wp.append(val)
#             safe_waypoints.append(clipped_wp)
# 
#         if clipped_occurred:
#             status = "RECOVERED"
#             notes.append("Stage 2: Target waypoints exceeded workspace limits and were clipped to safe boundaries.")
#             command.waypoints = safe_waypoints
# 
#         # --- Stage 3: Kinematic Continuity Check ---
#         if command.waypoints:
#             first_wp = command.waypoints[0]
#             for i, (curr_pos, target_pos) in enumerate(zip(state_obj.positions, first_wp)):
#                 if abs(target_pos - curr_pos) > 2.0:  # Cartesian step limit
#                     notes.append(f"Stage 3 Warning: Large trajectory delta detected on axis {i+1}.")
# 
#         elapsed_ms = (time.perf_counter() - t0) * 1000.0
#         receipt = HARMReceipt(
#             status=status,
#             is_safe=True,
#             catch_type="BOUNDS_CLIPPED" if clipped_occurred else None,
#             stage_failed=2 if clipped_occurred else None,
#             latency_ms=elapsed_ms,
#             command=command,
#             validation_notes=notes
#         )
#         return command, receipt
# 
# 
# # Alias for backward compatibility
# HARMEngine = HARM
# 
# 
# # ==========================================
# # STAGE 4: HIGH-FREQUENCY MOTOR CONTROLLER LOOP (100 Hz)
# # ==========================================
# 
# class LocalIKController:
#     """Helper class managing high-frequency local kinematics calculations at 100 Hz."""
#     def __init__(self, target_hz: float = 100.0):
#         self.target_hz = target_hz
#         self.time_per_cycle = 1.0 / target_hz
# 
#     def process_step(self, command: VLMCommand) -> Dict[str, Any]:
#         """Simulates 5ms Inverse Kinematic computation cycle."""
#         time.sleep(0.005)
#         return {
#             "action": command.action,
#             "applied_waypoint": command.waypoints[0] if command.waypoints else [0.0, 0.0, 0.0],
#             "confidence": command.confidence
#         }
# 
# async def ik_loop(bridge: Any, target_hz: float = 100.0):
#     """
#     High-frequency local motor loop running asynchronously at 100 Hz.
#     Features safety fallbacks for stale data and empty boot states.
#     """
#     print(f"🤖 [IK LOOP] Starting High-Speed Motor Controller Loop at {target_hz} Hz...")
#     controller = LocalIKController(target_hz=target_hz)
#     time_per_cycle = 1.0 / target_hz
# 
#     last_valid_command: Optional[VLMCommand] = None
#     iteration_timestamps: List[float] = []
# 
#     while True:
#         start_time = asyncio.get_running_loop().time()
#         iteration_timestamps.append(start_time)
# 
#         # 1. Evaluate StateBridge Mailbox Input & Apply Safety Fallbacks
#         if bridge.has_command():
#             current_command = await bridge.get_latest_command()
#             last_valid_command = current_command
#             execution_type = "🟢 FRESH"
# 
#         elif last_valid_command is not None:
#             current_command = last_valid_command
#             # Decay confidence level for stale data
#             current_command.confidence *= 0.95
#             execution_type = "🟡 STALE (Decaying Confidence)"
# 
#         else:
#             current_command = VLMCommand(
#                 action="HOLD",
#                 target_object="NONE",
#                 waypoints=[[0.0, 0.0, 0.0]],
#                 confidence=1.0,
#                 raw_response="INITIAL BOOT: Holding starting position."
#             )
#             execution_type = "🔴 HOLD STATE"
# 
#         # 2. Execute Local Kinematics Step
#         ik_result = controller.process_step(current_command)
# 
#         # Print telemetry periodically (every 50 cycles)
#         if len(iteration_timestamps) % 50 == 1:
#             print(f"⚙️ [IK CONTROLLER] Status: {execution_type} | Action: {ik_result['action']} | Waypoint: {ik_result['applied_waypoint']}")
# 
#         # 3. Enforce 100 Hz Loop Timing
#         elapsed_time = asyncio.get_running_loop().time() - start_time
#         remaining_sleep = time_per_cycle - elapsed_time
# 
#         if remaining_sleep > 0:
#             await asyncio.sleep(remaining_sleep)
#         else:
#             await asyncio.sleep(0)

import time
import json
from typing import List, Dict, Any, Tuple
from harm import HARM, RobotState, VLMCommand, LatencyProfiler

class SingleFrequencyBaseline:
    """
    Naive Single-Frequency Control Loop.
    Couples VLM inference, HARM safety validation, and IK calculations sequentially.
    """
    def __init__(self, harm_engine: HARM, target_ik_hz: float = 100.0):
        self.harm_engine = harm_engine
        self.target_ik_hz = target_ik_hz
        self.profiler = LatencyProfiler()

        # Telemetry storage
        self.ik_timestamps: List[float] = []
        self.vlm_timestamps: List[float] = []
        self.current_state = RobotState(positions=[0.0, 0.0, 0.0], timestamp=time.time())

    def _synchronous_vlm_call(self, image_source: str) -> str:
        """Simulates synchronous blocking VLM API call (~300ms latency)."""
        time.sleep(0.300)  # 300ms network & model inference delay
        return json.dumps({
            "action": "MOVE",
            "waypoints": [[0.25, -0.10, 0.45]],
            "confidence": 0.94
        })

    def _synchronous_ik_step(self, command: VLMCommand):
        """Simulates 5ms Inverse Kinematics math calculation."""
        time.sleep(0.005)  # 5ms IK execution lag
        if command.waypoints:
            target = command.waypoints[0]
            # Simple step interpolation toward target
            self.current_state.positions[0] += (target[0] - self.current_state.positions[0]) * 0.1
            self.current_state.positions[1] += (target[1] - self.current_state.positions[1]) * 0.1

    def run_baseline_test(self, duration_sec: float = 10.0) -> Dict[str, Any]:
        """Runs synchronous sequential control loop for a fixed duration."""
        print(f"🐢 [BASELINE] Starting Synchronous Single-Frequency Loop for {duration_sec}s...")
        self.ik_timestamps.clear()
        self.vlm_timestamps.clear()

        start_wall_time = time.time()

        while (time.time() - start_wall_time) < duration_sec:
            cycle_start = time.time()

            # 1. Synchronous VLM Call
            self.vlm_timestamps.append(cycle_start)
            raw_vlm_text = self._synchronous_vlm_call("cam_0.png")

            # 2. Synchronous HARM Validation
            t0 = time.perf_counter()
            validated_cmd, receipt = self.harm_engine.validate(raw_vlm_text, self.current_state)
            harm_latency_ms = (time.perf_counter() - t0) * 1000.0
            self.profiler.record_validation(receipt.status, harm_latency_ms)

            # 3. Synchronous IK Execution
            self.ik_timestamps.append(time.time())
            self._synchronous_ik_step(validated_cmd)

        total_elapsed = time.time() - start_wall_time
        total_ik_ticks = len(self.ik_timestamps)
        effective_ik_hz = total_ik_ticks / total_elapsed if total_elapsed > 0 else 0.0

        summary = {
            "duration_sec": round(total_elapsed, 2),
            "total_vlm_calls": len(self.vlm_timestamps),
            "total_ik_ticks": total_ik_ticks,
            "effective_ik_hz": round(effective_ik_hz, 2),
            "avg_harm_latency_ms": self.profiler.get_summary()["average_latency_ms"]
        }

        return summary


if __name__ == "__main__":
    harm = HARM(workspace_limits=[(-1.0, 1.0), (-1.0, 1.0), (0.0, 1.5)])
    baseline = SingleFrequencyBaseline(harm_engine=harm)
    results = baseline.run_baseline_test(duration_sec=10.0)

    print("\n==========================================")
    print("📊 SINGLE-FREQUENCY BASELINE METRICS")
    print("==========================================")
    print(f"  • Total Duration:     {results['duration_sec']} s")
    print(f"  • Total VLM Calls:    {results['total_vlm_calls']}")
    print(f"  • Total IK Ticks:     {results['total_ik_ticks']}")
    print(f"  • Effective IK Hz:    {results['effective_ik_hz']} Hz (Target: 100 Hz)")
    print(f"  • Avg HARM Latency:   {results['avg_harm_latency_ms']} ms")
    print("==========================================\n")