# -*- coding: utf-8 -*-
"""profiler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cuGN7ntFPaKsWK0GJ-lvgjpO5jeu8ZGX
"""

import numpy as np
import matplotlib.pyplot as plt
import csv

class LatencyProfiler:
    """
    A standalone, zero-bloat latency profiling class designed for the HRAF architecture.
    Measures, statistical profiles, and logs system execution percentiles.
    """
    def __init__(self):
        # Dictionary structure to cleanly track separate measurement labels independently
        self.metrics = {}

    def record(self, label: str, duration_ms: float):
        """Records a new execution timeline data point under a specific test label."""
        if label not in self.metrics:
            self.metrics[label] = []
        self.metrics[label].append(duration_ms)

    def stats(self, label: str) -> dict:
        """Calculates and returns core statistical percentiles using NumPy."""
        if label not in self.metrics or not self.metrics[label]:
            raise ValueError(f"No metrics recorded under the label: '{label}'")

        data = np.array(self.metrics[label])

        return {
            "p50": float(np.percentile(data, 50)),
            "p95": float(np.percentile(data, 95)),
            "p99": float(np.percentile(data, 99)),
            "mean": float(np.mean(data)),
            "std": float(np.std(data))
        }

    def plot(self, label: str):
        """Generates a distribution histogram highlighting tail latencies for HRAF paper logs."""
        if label not in self.metrics or not self.metrics[label]:
            raise ValueError(f"No metrics found to generate plot for label: '{label}'")

        data = self.metrics[label]
        stats = self.stats(label)

        plt.figure(figsize=(10, 5))
        n, bins, patches = plt.hist(data, bins=25, color='#00CC96', edgecolor='black', alpha=0.75, density=True)

        # Overlay absolute vertical indicator markers for our critical percentiles
        plt.axvline(stats["mean"], color='blue', linestyle='-', linewidth=1.5, label=f"Mean: {stats['mean']:.2f} ms")
        plt.axvline(stats["p50"], color='black', linestyle='--', linewidth=1.5, label=f"P50 (Median): {stats['p50']:.2f} ms")
        plt.axvline(stats["p95"], color='orange', linestyle='-.', linewidth=1.5, label=f"P95 Tail: {stats['p95']:.2f} ms")
        plt.axvline(stats["p99"], color='red', linestyle=':', linewidth=2, label=f"P99 Extreme: {stats['p99']:.2f} ms")

        plt.title(f"HRAF Latency Distribution Profile - [{label}]", fontsize=12, pad=15)
        plt.xlabel("Execution Duration (Milliseconds - ms)", fontsize=10)
        plt.ylabel("Density Probability", fontsize=10)
        plt.grid(True, linestyle=':', alpha=0.5)
        plt.legend(loc='upper right')
        plt.show()

    def export_csv(self, label: str, filepath: str):
        """Exports the raw recorded latencies for a given label to a CSV file."""
        if label not in self.metrics or not self.metrics[label]:
            raise ValueError(f"No metrics found to export for label: '{label}'")

        with open(filepath, mode='w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["Iteration", "Latency_ms"])
            for idx, latency in enumerate(self.metrics[label], start=1):
                writer.writerow([idx, latency])

        print(f"[Profiler Log] Successfully exported '{label}' data to: {filepath}")

# 1. Initialize the complete class
profiler = LatencyProfiler()

# 2. Add sample test metrics
np.random.seed(42)
simulated_vlm_latencies = np.random.lognormal(mean=3.5, sigma=0.6, size=100) + 200.0
for latency in simulated_vlm_latencies:
    profiler.record("simulated_vlm", latency)

# 3. Test the CSV export function that crashed before
profiler.export_csv("simulated_vlm", "vlm_latency_data.csv")