# -*- coding: utf-8 -*-
"""ros_node

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zHVsQWqdKJ8JNOAFAixFlcfhFR_EhaW
"""

#!/usr/bin/env python3
"""
HRAFMiddlewareNode - ROS 2 Python Node Wrapper
Subscribes to /camera/image_raw, executes ADCA+HARM validation, and publishes to /hraf/vlm_command.
"""

import json
import time
from typing import Dict, Any

# --- THIN ROS 2 WRAPPER WRAPPING ADCA + HARM ---
class HRAFMiddlewareNode:
    """
    Simulated thin ROS 2 Node container matching rclpy Node architecture.
    Handles ROS image subscription, ADCA+HARM execution, and ROS topic publishing.
    """
    def __init__(self, harm_pipeline_instance):
        print("🚀 [ROS 2 Node] Initializing HRAFMiddlewareNode...")
        self.harm_pipeline = harm_pipeline_instance

        # Simulated subscriber & publisher topic paths
        self.sub_topic = "/camera/image_raw"
        self.pub_topic = "/hraf/vlm_command"

        # Robot telemetry state tracking
        self.current_state = {"positions": [0.0, 0.0], "timestamp": time.time()}
        print(f"✅ [ROS 2 Node] Subscribed to {self.sub_topic} | Publishing to {self.pub_topic}")

    def image_callback(self, ros_image_msg: Dict[str, Any]) -> Dict[str, Any]:
        """
        Callback triggered when a new ROS Image message is published.
        Converts ROS message format, passes through ADCA+HARM, and returns ROS command msg.
        """
        print(f"\n📥 [ROS 2 Topic: {self.sub_topic}] Received frame ID: {ros_image_msg.get('frame_id', 'unknown')}")

        # 1. Message Conversion: Extract image data context
        image_context = ros_image_msg.get("data", "scene_frame")

        # 2. ADCA VLM Inference Step (Visual context -> Raw VLM payload)
        raw_vlm_output = self._run_adca_vlm_inference(image_context)

        # 3. HARM Engine Validation Step
        self.current_state["timestamp"] = time.time()
        validated_cmd, receipt = self.harm_pipeline.validate(
            raw_vlm_output,
            self.current_state
        )

        # 4. Message Conversion: Format into ROS VLMCommand output message
        ros_command_payload = {
            "topic": self.pub_topic,
            "action": validated_cmd.action,
            "waypoints": validated_cmd.waypoints,
            "confidence": validated_cmd.confidence,
            "harm_receipt": {
                "catch_type": receipt.catch_type,
                "stage_failed": receipt.stage_failed,
                "error_type": receipt.error_type
            }
        }

        print(f"📤 [ROS 2 Topic: {self.pub_topic}] Publishing validated VLMCommand message!")
        return ros_command_payload

    def _run_adca_vlm_inference(self, image_data: str) -> str:
        """Simulates ADCA VLM processing raw image input to produce structured output."""
        return json.dumps({
            "action": "MOVE",
            "waypoints": [[0.5, 0.0, 0.4]],
            "confidence": 0.95
        })

if __name__ == "__main__":
    print("HRAFMiddlewareNode script saved successfully!")