# -*- coding: utf-8 -*-
"""workspace_checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIXmbOmXuRqEshmL4Qq8v0NUqbvRNQzv
"""

import math

class WorkspaceChecker:
    def __init__(self, radius: float = 1.0):
        """
        Initializes the workspace boundaries for both Cartesian space
        and Joint space configurations.
        """
        # Layer 1: Cartesian Sphere Setup
        self.max_radius = radius

        # Layer 2: URDF Joint Angle Limits Setup (in radians)
        self.joint_limits = [
            {"min": -math.pi,      "max": math.pi},       # Joint 1: -180° to +180°
            {"min": -math.pi / 2,  "max": math.pi / 2},   # Joint 2: -90° to +90°
            {"min": -2.6,          "max": 2.6}            # Joint 3: -150° to +150°
        ]
        print("📐 Workspace initialized with Cartesian sphere bounds and URDF joint limit boundaries.")

    def is_reachable(self, point_3d: tuple[float, float, float]) -> bool:
        """LAYER 1: Distance check formula."""
        x, y, z = point_3d
        distance = math.sqrt(x**2 + y**2 + z**2)
        return distance <= self.max_radius

    def clip_to_boundary(self, point_3d: tuple[float, float, float]) -> tuple[float, float, float]:
        """LAYER 1 FAIL-SAFE: Boundary clipping adjustment."""
        x, y, z = point_3d
        distance = math.sqrt(x**2 + y**2 + z**2)
        if distance <= self.max_radius or distance == 0.0:
            return (x, y, z)
        scale_factor = self.max_radius / distance
        return (x * scale_factor, y * scale_factor, z * scale_factor)

    def verify_joint_limits(self, joint_angles: list[float]) -> bool:
        """LAYER 2: Joint Space Angle Constraint Loop."""
        if len(joint_angles) != len(self.joint_limits):
            print(f"⚠️ Safety Alarm: Input counts ({len(joint_angles)}) don't match hardware configuration.")
            return False

        for i, angle in enumerate(joint_angles):
            limits = self.joint_limits[i]
            if angle < limits["min"] or angle > limits["max"]:
                print(f"🚨 URDF Limit Violation: Joint {i+1} commanded to {math.degrees(angle):.1f}° | Allowed: {math.degrees(limits['min'])}° to {math.degrees(limits['max'])}°")
                return False
        return True

# --- COMBINED TEST RUNNER (ALL LAYERS WORKING TOGETHER) ---
if __name__ == "__main__":
    checker = WorkspaceChecker(radius=1.0)
    print("-" * 50)

    # 🔴 RUNNING LAYER 1 TESTS (Cartesian Coordinates)
    print("🏃 RUNNING LAYER 1 TESTS (Cartesian Coordinates)...")
    p1 = (0.5, 0.3, 0.1)
    print(f"📍 Point {p1} reachable? -> {checker.is_reachable(p1)}")

    p2 = (2.0, 0.0, 0.0)
    print(f"🚨 Point {p2} reachable? -> {checker.is_reachable(p2)}")

    fixed_p2 = checker.clip_to_boundary(p2)
    print(f"🛡️ HARM Action: Shifted {p2} -> Safe point: {fixed_p2}")
    print("-" * 50)

    # 🔵 RUNNING LAYER 2 TESTS (Joint Space Angle Constraints)
    print("🏃 RUNNING LAYER 2 TESTS (Joint Space Angle Constraints)...")
    safe_pose = [0.0, 0.5, -1.0]
    print(f"✅ Safe Posture verification result: {checker.verify_joint_limits(safe_pose)}")

    dangerous_pose = [0.0, 2.0, -1.0]
    print(f"❌ Dangerous Posture verification result: {checker.verify_joint_limits(dangerous_pose)}")
    print("-" * 50)

!pip install hypothesis

"""##**Testing Code Block**"""

import math
from hypothesis import given, strategies as st, assume, note

# --- 1. OUR CORE THURSDAY WORKSPACE CHECKER CLASS ---
class WorkspaceChecker:
    def __init__(self, radius: float = 1.0):
        self.max_radius = radius
        self.joint_limits = [
            {"min": -math.pi,      "max": math.pi},       # Joint 1
            {"min": -math.pi / 2,  "max": math.pi / 2},   # Joint 2
            {"min": -2.6,          "max": 2.6}            # Joint 3
        ]

    def is_reachable(self, point_3d: tuple[float, float, float]) -> bool:
        x, y, z = point_3d
        distance = math.sqrt(x**2 + y**2 + z**2)
        return distance <= self.max_radius

    def clip_to_boundary(self, point_3d: tuple[float, float, float]) -> tuple[float, float, float]:
        x, y, z = point_3d
        distance = math.sqrt(x**2 + y**2 + z**2)
        if distance <= self.max_radius or distance == 0.0:
            return (x, y, z)
        scale_factor = self.max_radius / distance
        return (x * scale_factor, y * scale_factor, z * scale_factor)


# --- 2. CONNECTING WEDNESDAY'S PROPERTY-BASED TEST ---
@given(
    x=st.floats(min_value=-10.0, max_value=10.0),
    y=st.floats(min_value=-10.0, max_value=10.0),
    z=st.floats(min_value=-10.0, max_value=10.0)
)
def test_production_workspace_property(x: float, y: float, z: float):
    # Initialize the production class instance
    checker = WorkspaceChecker(radius=1.0)

    # Skip invalid mathematical markers (NaN or Infinity)
    assume(not math.isnan(x) and not math.isinf(x))
    assume(not math.isnan(y) and not math.isinf(y))
    assume(not math.isnan(z) and not math.isinf(z))

    # Skip origin (0,0,0) to prevent division-by-zero math boundaries
    assume(x != 0.0 or y != 0.0 or z != 0.0)

    # Extract original inputs for note logs
    input_point = (x, y, z)

    # Run the fuzz data directly through the real production safety checker methods
    clipped_x, clipped_y, clipped_z = checker.clip_to_boundary(input_point)
    final_distance = math.sqrt(clipped_x**2 + clipped_y**2 + clipped_z**2)

    # Log information if a failure occurs
    note(f"Fuzz Input: ({x:.4f}, {y:.4f}, {z:.4f})")
    note(f"Class Return: ({clipped_x:.4f}, {clipped_y:.4f}, {clipped_z:.4f}) -> Output Distance: {final_distance:.4f}m")

    # THE GOLDEN INVARIANT PROPERTY: Must always scale back cleanly within the 1.0m physical limit sphere
    assert final_distance <= 1.00001


# --- 3. EXECUTION SUITE ---
if __name__ == "__main__":
    print("🚀 Connecting Wednesday property fuzzing to Thursday's production file class...")
    try:
        test_production_workspace_property()
        print("✅ SUCCESS: The final WorkspaceChecker class successfully passed all 100 random boundary attacks!")
    except Exception as e:
        print("❌ INTEGRATION TEST FAILED:")
        print(e)